### ISSUE TITLE
Remove unnecessary functions like `find` and `replace`

### ISSUE THREAD

**Issue by fhightower** [democritus-project/d8s-regexes#5]
There is no reason that I can see to keep these around as they are just wrappers around python's regex module.

**Comment by ckmganesh** [comment]
I would like to do this. Can you assign this to me

**Comment by fhightower** [comment]
@ckmganesh : Absolutely, thank you! If you have any questions, please do not hesitate to ask. As stated in the issue's title, the goal is to remove some of the simple functions from this library. I'd like to remove them because developers should just use the built-in [re](https://docs.python.org/3/library/re.html) library. I think the following functions should be removed:

- regex_escape
- replace
- find

If you think any of these ^ should not be removed or if you find any others you think should not be removed, let me know.

Thanks again! I'm excited to have some help on this project.

**Comment by ckmganesh** [comment]
Yeah sure.

**Comment by fhightower** [comment]
Perfect, thanks @ckmganesh !
